version: '3'
services:
  redis:
    image: redis
    container_name: redis-containers
    ports:
      - "6379:6379"
  
  app:
    build: .
    container_name: app-container
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "3000:3000"
